reformat

diff --git a/assets/bin/cpk-apt-install b/assets/bin/cpk-apt-install
--- a/assets/bin/cpk-apt-install
+++ b/assets/bin/cpk-apt-install
@@ -3,8 +3,8 @@
 set -e
 
 if [ "$#" -ne 1 ]; then
-    >&2 echo "ERROR: You need to pass a dependencies list file as an argument to cpk-apt-install.";
-    exit 1;
+    echo >&2 "ERROR: You need to pass a dependencies list file as an argument to cpk-apt-install."
+    exit 1
 fi
 
 PACKAGES_LIST=$1
@@ -12,10 +12,10 @@ PACKAGES=$(awk -F: '/^[^#]/ { print $1 }' $PACKAGES_LIST | uniq)
 HAS_PACKAGES=$(echo $PACKAGES | sed '/^\s*#/d;/^\s*$/d' | wc -l)
 
 if [ $HAS_PACKAGES -eq 1 ]; then
-  echo "Installing packages via APT..."
-  apt-get update
-  apt-get install -y --no-install-recommends $PACKAGES
-  rm -rf /var/lib/apt/lists/*
+    echo "Installing packages via APT..."
+    apt-get update
+    apt-get install -y --no-install-recommends $PACKAGES
+    rm -rf /var/lib/apt/lists/*
 else
-  echo "No packages to install via APT."
+    echo "No packages to install via APT."
 fi
diff --git a/assets/bin/cpk-install-launchers b/assets/bin/cpk-install-launchers
--- a/assets/bin/cpk-install-launchers
+++ b/assets/bin/cpk-install-launchers
@@ -11,8 +11,8 @@ INSTALL_DIR=/usr/local/bin
 
 # check LAUNCHERS_DIR
 if [[ ! -d ${LAUNCHERS_DIR} ]]; then
-  >&2 echo "ERROR: The path ${LAUNCHERS_DIR} does not exists or it is not a directory";
-  exit 1;
+    echo >&2 "ERROR: The path ${LAUNCHERS_DIR} does not exists or it is not a directory"
+    exit 1
 fi
 
 # create destination if it does not exist
@@ -21,24 +21,24 @@ mkdir -p ${INSTALL_DIR}
 # install launchers
 n=0
 for filepath in "${LAUNCHERS_DIR}"/*; do
-  base=$(basename "${filepath}")
-  filename=${base%.*}
-  destination="${INSTALL_DIR}/cpk-launcher-${filename}"
-  # remove overlapping link (if any)
-  rm -f "${destination}"
-  # create a link to the launcher
-  ln -s "${filepath}" "${destination}"
-  if [[ ! -x "${filepath}" ]]; then
-    # the launcher is not executable, check if it has a shebang
-    if [[ "$(head -c 2 "${filepath}")" = "#!" ]]; then
-      chmod +x "${destination}"
-    else
-      >&2 echo "ERROR: The launcher '${filename}' is not executable and does not have a shebang";
-      exit 2
+    base=$(basename "${filepath}")
+    filename=${base%.*}
+    destination="${INSTALL_DIR}/launcher-${filename}"
+    # remove overlapping link (if any)
+    rm -f "${destination}"
+    # create a link to the launcher
+    ln -s "${filepath}" "${destination}"
+    if [[ ! -x "${filepath}" ]]; then
+        # the launcher is not executable, check if it has a shebang
+        if [[ "$(head -c 2 "${filepath}")" == "#!" ]]; then
+            chmod +x "${destination}"
+        else
+            echo >&2 "ERROR: The launcher '${filename}' is not executable and does not have a shebang"
+            exit 2
+        fi
     fi
-  fi
-  ((n++))
+    ((n++))
 done
 
 # everything should be OK
-echo "DONE: Installed ${n} launchers!";
+echo "DONE: Installed ${n} launchers!"
diff --git a/assets/bin/cpk-pip3-install b/assets/bin/cpk-pip3-install
--- a/assets/bin/cpk-pip3-install
+++ b/assets/bin/cpk-pip3-install
@@ -3,7 +3,7 @@
 set -e
 
 if [ "$#" -ne 1 ]; then
-    >&2 echo "ERROR: You need to pass a dependencies list file as an argument to cpk-pip3-install."
+    echo >&2 "ERROR: You need to pass a dependencies list file as an argument to cpk-pip3-install."
     exit 1
 fi
 
@@ -12,8 +12,8 @@ PACKAGES=$(awk -F: '/^[^#]/ { print $1 }' $PACKAGES_LIST | uniq)
 HAS_PACKAGES=$(echo $PACKAGES | sed '/^\s*#/d;/^\s*$/d' | wc -l)
 
 if [ $HAS_PACKAGES -eq 1 ]; then
-  echo "Installing packages via PIP3..."
-  pip3 install -r ${PACKAGES_LIST}
+    echo "Installing packages via PIP3..."
+    pip3 install -r ${PACKAGES_LIST}
 else
-  echo "No packages to install via APT."
+    echo "No packages to install via PIP3."
 fi
